### ISSUE TITLE
New options

### ISSUE THREAD

**Issue by alec1o** [FajarKim/github-readme-profile#377]
### Is your feature request related to a problem? Please describe.

Support new options:
- tittle_text="Hi" (override text if not empty)
- title_align=left|center|right (or 1, 2, 3)
- revert=true|false (invert display order, content to left and image to right)

**Comment by FajarKim** [comment]
> ### Is your feature request related to a problem? Please describe.
> 
> Support new options:
> - tittle_text="Hi" (override text if not empty)
> - title_align=left|center|right (or 1, 2, 3)
> - revert=true|false (invert display order, content to left and image to right)

Sorry I am only replying to you now 🙏🏻. I am currently unable to fulfill your request as I am currently very busy. So, can you work on this? I would really appreciate your contribution to improve the experience of using this tool.

**Comment by FajarKim** [comment]
> ### Is your feature request related to a problem? Please describe.
> 
> Support new options:
> - tittle_text="Hi" (override text if not empty)
> - title_align=left|center|right (or 1, 2, 3)
> - revert=true|false (invert display order, content to left and image to right)

For the `title` and `revert` options I have worked on it. Sorry because I can't work on the `title_align` option due to display issues. Thank you for submitting a new feature. In the future, I hope you will contribute more to develop this tool. Thank you 🙏🏻
