### ISSUE TITLE
Fix the Header 

### ISSUE THREAD

**Issue by srinidhifd** [FajarKim/github-readme-profile#462]
### Describe the bug

The logo currently covers half of the page, which affects the user experience.

 Screenshot :

![image](https://github.com/user-attachments/assets/1f5eb059-c7cb-444c-a192-58f3805a3937)

### Expected behavior

A better approach would be to align the logo to the left side in the header, with the text “GitHub Readme Profile Generator” positioned next to it. This layout will create a more balanced and user-friendly interface, enhancing the overall experience.

### Screenshots / Live demo link

![image](https://github.com/user-attachments/assets/c49a6cbc-1e9e-4bfb-94a7-ceb7af58c3e2)

@FajarKim I would like to work on this issue. Please assign this to be under Hacktoberfest label

**Comment by srinidhifd** [comment]
@FajarKim Can you assign the issue to me, you have assigned the issue to yourself.[self-assign]

**Comment by srinidhifd** [comment]
@FajarKim  In the recent changes [PR] , it is almost completed. It would be better if you could close this issue. I will find some other issues.
Screenshot :
![image](https://github.com/user-attachments/assets/1f4f9cd1-564d-4c33-a8ae-ca35bb561eb8)

**Comment by FajarKim** [comment]
> @FajarKim  In the recent changes [PR] , it is almost completed. It would be better if you could close this issue. I will find some other issues.
> Screenshot :
> ![image](https://github.com/user-attachments/assets/1f4f9cd1-564d-4c33-a8ae-ca35bb561eb8)
> 

Okay I will close this issue. Thank you for reporting this. Hopefully you can contribute to the next update to improve the experience of using this tool. Thanks again 🙏🏻💪🏻
